services:

  # =========================================================================
  # INFRASTRUCTURE DE BASE (PAYS : BRÉSIL)
  # =========================================================================

  # Base de données PostgreSQL pour le pays "Brésil"
  postgres-bresil:
    image: postgres:15
    container_name: futurekawa-db-bresil
    environment:
      POSTGRES_USER: futurekawa
      POSTGRES_PASSWORD: futurekawa123
      POSTGRES_DB: futurekawa_bresil
    ports:
      - "5432:5432"
    volumes:
      - postgres_bresil_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U futurekawa -d futurekawa_bresil"]
      interval: 5s
      timeout: 5s
      retries: 5


# # Broker MQTT Mosquitto pour le pays "Brésil"
  mosquitto-bresil:
   image: eclipse-mosquitto:2
   container_name: futurekawa-mqtt-bresil
   ports:
     - "1883:1883"
   volumes:
     - ./backend-pays/src/mosquitto.conf:/mosquitto/config/mosquitto.conf

  # Backend FastAPI pour le pays "Brésil"
  backend-pays-bresil:
    build:
      context: ./backend-pays/src
    container_name: futurekawa-backend-bresil
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://futurekawa:futurekawa123@postgres-bresil:5432/futurekawa_bresil
      MQTT_BROKER: mosquitto-bresil
      MQTT_PORT: 1883
    depends_on:
      postgres-bresil:
        condition: service_healthy
      mosquitto-bresil:
        condition: service_started
    restart: always

  # Simulateur IoT (ESP32) publiant vers le broker du Brésil
  simulateur-bresil:
    build:
      context: ./simulateur
    container_name: futurekawa-sim-bresil
    command: python simulateur_esp32.py --pays bresil --broker mosquitto-bresil --port 1883 --intervalle 10
    depends_on:
      - mosquitto-bresil
    restart: always

  # =========================================================================
  # BACKEND CENTRAL (SIÈGE)
  # =========================================================================

  # Backend Central (Siège) qui consolide les API pays
  backend-central:
    build:
      context: ./backend-central/src
    container_name: futurekawa-backend-central
    ports:
      - "8010:8000"  
    environment:
      COUNTRY_BRESIL_URL: http://backend-pays-bresil:8000
      COUNTRY_EQUATEUR_URL: http://backend-pays-equateur:8000
      COUNTRY_COLOMBIE_URL: http://backend-pays-colombie:8000
    depends_on:
      - backend-pays-bresil
    restart: always

  # =========================================================================
  # FRONTEND_WEB CENTRAL (SIÈGE)
  # =========================================================================
  # TODO

volumes:
  postgres_bresil_data: