services:
  simulateur-bresil:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: futurekawa-sim-bresil
    command: python simulateur_esp32.py --pays bresil --broker futurekawa-mqtt --port 1883 --intervalle 10
    networks:
      - futurekawa-network
    restart: on-failure

networks:
  futurekawa-network:
    external: true
    name: backend-pays_default